Fixed and added some sidebar buttons
Pedro-Gregorio/TubeMod pull request #34
Opened 2024-09-27 18:37 UTC by Perseus333

- Made some xpaths to some sidebar buttons more robust by relying on hrefs instead of index numbers.
- Fixed the shorts button so that it works on firefox aswell
- Added a toggle to disable the courses button in the sidebar

2024-09-27 20:01 UTC, Pedro-Gregorio requested changes
Otherwise we're also hiding the Subscriptions channels, and that isn't ideal.

2024-09-27 20:01 UTC, Pedro-Gregorio commented on scripts/content.js
> +    selector: "//ytd-guide-entry-renderer[a[starts-with(@href, '/@')]]",
```suggestion
    selector: "//div[@id='section-items']/ytd-guide-entry-renderer[a[starts-with(@href, '/@')]]",
```

2024-09-27 20:04 UTC, Perseus333 commented
Thanks for spotting that, I guess that during testing I also had the Subscriptions channels hidden so I didn't notice.

2024-09-28 10:28 UTC, Perseus333 commented
Now it has support for hiding the "Your movies & TV" section in the sidebar thanks to https://github.com/Pedro-Gregorio/TubeMod/issues/40, and https://github.com/Pedro-Gregorio/TubeMod/issues/40#issuecomment-2380576180 for providing the href. This is currently untested but it *should* work.

2024-09-28 10:44 UTC, Rashnain commented
The "Hide Courses button" has also the wrong id, it acutally has `for="my-videos"` instead of `for="courses"`

2024-09-28 10:48 UTC, Rashnain commented
When fixed the "Hide Your movies & TV Button" works well. I can't test for "Hide Courses Button" because I don't have it.

2024-09-28 10:48 UTC, Perseus333 commented
Should be fixed, it also happened to my-movies-and-tv. Thansk for pointing it out

2024-09-28 10:48 UTC, Perseus333 commented
> When fixed the "Hide Your movies & TV Button" works well. I can't test for "Hide Courses Button" because I don't have it.

It works for me.

2024-09-28 18:11 UTC, Pedro-Gregorio commented
@Perseus333 thank you for this! Adding it to V1.5.0 :)
I don't have the movies and tv button, but I'll trust @Rashnain review on that end!

@Perseus333 would you mind sharing a print screen of the sidebar (without anything hidden :D) just to ensure the order is correct.

2024-09-28 18:14 UTC, Perseus333 commented
> @Perseus333 would you mind sharing a print screen of the sidebar (without anything hidden :D) just to ensure the order is correct.

Here you go (btw, I don't know how to make this images smaller, sorry for the size):
![image](https://github.com/user-attachments/assets/8f530ebb-b313-424b-b4e1-dc13070114b6)

2024-09-28 18:17 UTC, Pedro-Gregorio commented
Wait, I'm confused. Where's the "Your movies & TV" button? 🤔

2024-09-28 18:19 UTC, Perseus333 commented
> Wait, I'm confused. Where's the "Your movies & TV" button? 🤔

I don't know. But it should either be above or below courses. I don't think there is anyone that has both. Although I can provide a link to a course so that someone can add to their library so that they have access to the "courses" sidebar button and report which is the correct order.

2024-09-28 18:26 UTC, Pedro-Gregorio commented
My bad, just found the issue where you and Rashnain talked about it :)
Once again, thank you both!

2024-09-28 18:27 UTC, Pedro-Gregorio approved these changes

2024-09-28 18:27 UTC, merged